### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by GennadiyShpak** [GennadiyShpak/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by GennadiyShpakTwink** [comment]
... that God-given skill is not the main one. It's important not to give up under any circumstances. And remember that only by trying your best can you achieve something. Even if the result is disastrous.

**Comment by GennadiyShpakTwink** [comment]
The dirtiest thing about boxing is the morning after a fight. After the fight, you are one continuous wound. I would like to call a taxi to get to the toilet.

**Comment by GennadiyShpakTwink** [comment]
The dirtiest thing about boxing is the morning after a fight. After the fight, you are one continuous wound. I would like to call a taxi to get to the toilet.

**Comment by GennadiyShpakTwink** [comment]
Fear is a boxer's best friend! And there is nothing to be ashamed of ... Fear, like fire, burns inside you. If you learn to control him, you will feel heat in your chest, but if he controls you, he will burn you and everything around.
