### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by GennadiyShpak** [GennadiyShpak/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by GennadiyShpakTwink** [comment]
https://twitter.com/rockybalboa62
https://www.facebook.com/ROCKYBALBOA1976/
rockybalboa@gmai.com
