### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by GennadiyShpak** [GennadiyShpak/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by GennadiyShpakTwink** [comment]
Rocky Balboa - Spyder Rico
November 25, 1975
Balboa won by knockout in the 2nd round
Status: Demonstration fight.

Rocky Balboa - Apollo Creed
Date: January 1, 1976
Result: Creed wins by split decision.
Status: Fight for the world heavyweight title

Rocky Balboa - Apollo Creed 2
Date: November 25, 1976
Result: Balboa won by knockout in the 15th round
Status: Fight for the world heavyweight title

Rocky Balboa - Vito Soto
Date: June 1977
Result: Balboa won by knockout 
Status: Fight for the World Heavyweight Championship (Balboa's 4th Defense)

Rocky Balboa - Germany Marko Kretschmann
Date: December 1977
Result: Balboa won by knockout in the 3rd round
Status: Fight for the World Heavyweight Championship (Balboa's 5th Defense)

Rocky Balboa - Dave Fossan
Date: March 1978
Result: Balboa won by knockout in the 2nd round
Status: Fight for the world heavyweight title (6th defense of Balboa)

Rocky Balboa - Jamal Ben Saddick
Date: September 1978
Result: Balboa won by knockout in the 3rd round
Status: Fight for the world heavyweight title (7th defense of Balboa)

Rocky Balboa - United States of America Joe Greene
Date: April 1979
Result: Balboa won by knockout in the 2nd round
Status: Fight for the World Heavyweight Championship (Balboa's 8th Defense)

Rocky Balboa - Matt Dilaru
Date: October 1979
Result: Balboa won by knockout in the 5th round
Status: Fight for the World Heavyweight Championship (Balboa's 9th Defense)

Rocky Balboa - Philip Hammerman
Date: August 1980
Result: Balboa won by knockout in the 3rd round
Status: Fight for the World Heavyweight Championship (Balboa's 10th Defense)

Rocky Balboa - James (Clubber) Lang
Date: February 1981
Result: Lang wins by knockout in the 2nd round
Status: Fight for the world heavyweight title (11th defense of Balboa).

Rocky Balboa - James (Clubber) Lang 2
Date: 1982
Result: Balboa won by knockout in the 3rd round
Status: Fight for the World Heavyweight Championship (Lang's 1st Defense).

Rocky Balboa - Ivan Drago
Date: December 25, 1985
Result: Balboa won by knockout in the 15th round
Status: Demonstration fight..

Rocky Balboa - United States of America Mason Dixon
Venue: Las Vegas
Date: 2006
Result: Dixon wins by unanimous decision

.
