### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by GennadiyShpak** [GennadiyShpak/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by GennadiyShpakTwink** [comment]
Rocky Balboa marries Adriana Pennino in early 1976. They were married for 26 years until Adriana died of cancer. Her brother Polly was Rocky's best friend. From Adriana, Rocky has a son, Robert (Rocky) Balboa Jr., who, unlike his father, uses the name Robert. He was born in 1976. In the eighth film, it is revealed that Robert now has a son, Logan, and at the end of the film, Rocky sees him for the first time in his life, although the boy is already several years old.

Coach career
In 1983, Rocky was assistant coach to Tony "Duke" Evers for the first time. Together they coached Apollo Creed against Ivan Drago. At the request of the injured Creed, Rocky does not stop the fight. As a result, Apollo dies.
In 1990, Rocky leads a simple street guy, Tommy Gunn, to the world title. However, Gunn betrays Rocky by going to another promoter.

In 2015, Apollo Creed's illegitimate son, Adonis Creed, persuades Rocky to become his coach. As a result, Creed almost becomes world champion, losing only by split decision.
In 2018, Rocky again coaches Adonis.
